export const facturasVentaOtrosACC = `
    SELECT
        CODIGO,
        X.TALLA,
        X.DESCRIPCION,
        X.CODBARRAS,
        X.DESCRIP_ADIC AS DETALLE,
        X.PAIS_ORIGEN AS ORIGEN,
        X.COMPOESP,
        X.MARCA,
        X.CANTIDAD,
        X.PRECIO,
        X.TOTAL,
        X.TOTAL_NETO,
        X.TOTAL_BRUTO,
        X.TOTAL_UNIDADES
    FROM
        (
            SELECT
                (SELECT ART.REFPROVEEDOR FROM BBW_NEW.DBO.ARTICULOS ART WHERE ART.CODARTICULO = LIN.CODARTICULO) AS CODIGO,
                CAB.FECHA,
                CAB.FECHARECEPCION,
                LIN.CODALMACEN,
                CAB.NUMSERIE,
                CAB.NUMALBARAN,
                LIN.TALLA,
                LIN.COLOR,
                (SELECT ART.CODBARRAS FROM BBW_NEW.DBO.ARTICULOSLIN ART WHERE ART.CODARTICULO = LIN.CODARTICULO AND ART.TALLA = LIN.TALLA AND LIN.COLOR = ART.COLOR) AS CODBARRAS,
                (SELECT MAX(M.DESCRIPCION) FROM BBW_NEW.DBO.MARCA M, BBW_NEW.DBO.ARTICULOS A WHERE M.CODMARCA = A.MARCA AND A.CODARTICULO = LIN.CODARTICULO) AS MARCA,
                (SELECT ART.DESCRIPCION FROM BBW_NEW.DBO.ARTICULOS ART WHERE ART.CODARTICULO = LIN.CODARTICULO) AS DESCRIPCION,
                (SELECT D.DESCRIPCION FROM BBW_NEW.DBO.DEPARTAMENTO D, BBW_NEW.DBO.ARTICULOS S WHERE D.NUMDPTO = S.DPTO AND S.CODARTICULO = LIN.CODARTICULO) AS DEPARTAMENTO,
                ACL.*,
                LIN.UNIDADESTOTAL AS CANTIDAD,
                (LIN.TOTAL * CAB.FACTORMONEDA) / LIN.UNIDADESTOTAL AS PRECIO,
                LIN.DTO,
                LIN.TOTAL * CAB.FACTORMONEDA AS TOTAL,
                LIN.TOTAL AS TOTAL_LOC,
                (SELECT SUM(AVL.TOTAL * AVC.FACTORMONEDA) FROM ALBVENTALIN AVL INNER JOIN ALBVENTACAB AVC ON AVC.NUMALBARAN = AVL.NUMALBARAN AND AVC.NUMSERIE = AVL.NUMSERIE AND AVC.N = AVL.N WHERE AVC.NUMSERIEFAC LIKE @NUMSERIEFAC AND AVC.NUMFAC LIKE @NUMFAC) TOTAL_NETO,
                (SELECT SUM((AVL.PRECIO * AVC.FACTORMONEDA) * AVL.UNIDADESTOTAL) FROM ALBVENTALIN AVL INNER JOIN ALBVENTACAB AVC ON AVC.NUMALBARAN = AVL.NUMALBARAN AND AVC.NUMSERIE = AVL.NUMSERIE AND AVC.N = AVL.N WHERE AVC.NUMSERIEFAC LIKE @NUMSERIEFAC AND AVC.NUMFAC LIKE @NUMFAC) TOTAL_BRUTO,
                (SELECT SUM(AVL.UNIDADESTOTAL) FROM ALBVENTALIN AVL INNER JOIN ALBVENTACAB AVC ON AVC.NUMALBARAN = AVL.NUMALBARAN AND AVC.NUMSERIE = AVL.NUMSERIE AND AVC.N = AVL.N WHERE AVC.NUMSERIEFAC LIKE @NUMSERIEFAC AND AVC.NUMFAC LIKE @NUMFAC) TOTAL_UNIDADES
            FROM
                BBW_NEW.DBO.ALBVENTACAB AS CAB
            INNER JOIN
                BBW_NEW.DBO.ALBVENTALIN AS LIN ON (CAB.NUMSERIE = LIN.NUMSERIE AND CAB.NUMALBARAN = LIN.NUMALBARAN AND CAB.N = LIN.N)
            INNER JOIN
                BBW_NEW.DBO.ARTICULOSCAMPOSLIBRES ACL ON (ACL.CODARTICULO = LIN.CODARTICULO)
            WHERE
                CAB.NUMFAC LIKE @NUMFAC
                AND CAB.NUMSERIEFAC LIKE @NUMSERIEFAC
        ) AS X
`