export const facturasVentaColombia = `
    SELECT
        CODIGO,
        X.TALLA,
        X.DESCRIPCION,
        X.CODBARRAS,
        X.DESCRIP_ADIC AS DETALLE,
        X.PAIS_ORIGEN AS ORIGEN,
        X.COMPOESP,
        X.MARCA,
        X.CANTIDAD,
        X.PRECIO,
        X.TOTAL
    FROM
        (
            SELECT
                (SELECT ART.REFPROVEEDOR FROM BBW_NEW.DBO.ARTICULOS ART WHERE ART.CODARTICULO = LIN.CODARTICULO) AS CODIGO,
                CAB.FECHA,
                CAB.FECHARECEPCION,
                LIN.CODALMACEN,
                CAB.NUMSERIE,
                CAB.NUMALBARAN,
                LIN.TALLA,
                LIN.COLOR,
                (SELECT ART.CODBARRAS FROM BBW_NEW.DBO.ARTICULOSLIN ART WHERE ART.CODARTICULO = LIN.CODARTICULO AND ART.TALLA = LIN.TALLA AND LIN.COLOR = ART.COLOR) AS CODBARRAS,
                (SELECT MAX(M.DESCRIPCION) FROM BBW_NEW.DBO.MARCA M, BBW_NEW.DBO.ARTICULOS A WHERE M.CODMARCA = A.MARCA AND A.CODARTICULO = LIN.CODARTICULO) AS MARCA,
                (SELECT ART.DESCRIPCION FROM BBW_NEW.DBO.ARTICULOS ART WHERE ART.CODARTICULO = LIN.CODARTICULO) AS DESCRIPCION,
                (SELECT D.DESCRIPCION FROM BBW_NEW.DBO.DEPARTAMENTO D, BBW_NEW.DBO.ARTICULOS S WHERE D.NUMDPTO = S.DPTO AND S.CODARTICULO = LIN.CODARTICULO) AS DEPARTAMENTO,
                ACL.*,
                LIN.UNIDADESTOTAL AS CANTIDAD,
                (LIN.TOTAL * CAB.FACTORMONEDA) / LIN.UNIDADESTOTAL AS PRECIO,
                LIN.DTO,
                LIN.TOTAL * CAB.FACTORMONEDA AS TOTAL,
                LIN.TOTAL AS TOTAL_LOC
            FROM
                BBW_NEW.DBO.ALBVENTACAB AS CAB
            INNER JOIN
                BBW_NEW.DBO.ALBVENTALIN AS LIN ON (CAB.NUMSERIE = LIN.NUMSERIE AND CAB.NUMALBARAN = LIN.NUMALBARAN AND CAB.N = LIN.N)
            INNER JOIN
                BBW_NEW.DBO.ARTICULOSCAMPOSLIBRES ACL ON (ACL.CODARTICULO = LIN.CODARTICULO)
            WHERE
                CAB.NUMFAC = @NUMFAC
                AND CAB.NUMSERIEFAC = @NUMSERIEFAC
        ) AS X;
`