export const reporteGeneral = `
    WITH TotalesAgregados AS (
        SELECT
            CAB.NUMSERIEFAC,
            CAB.NUMFAC,
            SUM(LIN.TOTAL * CAB.FACTORMONEDA) AS TOTAL_NETO,
            SUM((LIN.PRECIO * CAB.FACTORMONEDA) * LIN.UNIDADESTOTAL) AS TOTAL_BRUTO,
            SUM(LIN.UNIDADESTOTAL) AS TOTAL_UNIDADES
        FROM
            BBW_NEW.DBO.ALBVENTACAB AS CAB
        INNER JOIN
            BBW_NEW.DBO.ALBVENTALIN AS LIN ON CAB.NUMALBARAN = LIN.NUMALBARAN
                                        AND CAB.NUMSERIE = LIN.NUMSERIE
                                        AND CAB.N = LIN.N
        WHERE
            CAB.NUMSERIEFAC LIKE @NUMSERIEFAC
            AND CAB.NUMFAC = @NUMFAC
        GROUP BY
            CAB.NUMSERIEFAC,
            CAB.NUMFAC
    )
    SELECT
        LIN.REFERENCIA AS ARTICULO,
        ART.REFPROVEEDOR AS CODIGO,
        LIN.TALLA AS CONTENIDO,
        LIN.COLOR,
        ARL.CODBARRAS AS CODBARRAS,
        M.DESCRIPCION AS MARCA,
        ART.DESCRIPCION AS DESCRIPCION,
        D.DESCRIPCION AS DEPARTAMENTO,
        ACL.DESCRIP_ADIC AS DETALLE,
        ACL.COMPOESP AS COMPOSICION,
        CASE
            WHEN (CLI.PAIS = 'COSTA RICA') THEN ACL.NUM_REG_SAN_CR
            WHEN (CLI.PAIS = 'EL SALVADOR') THEN ACL.NUM_REG_SAN_SAL
            ELSE ACL.NUM_REG_SAN_PAN
        END AS NUM_REG,
        CASE
            WHEN (CLI.PAIS = 'COSTA RICA') THEN ACL.NOM_REG_SAN_CR
            WHEN (CLI.PAIS = 'EL SALVADOR') THEN ACL.NOM_REG_SAN_SAL
            ELSE ACL.NOM_REG_SAN_PMA
        END AS DESCRIPCION_REG,
        CASE
            WHEN (CLI.PAIS = 'COSTA RICA') THEN ACL.ESENCIA_REG_SAN_CR
            WHEN (CLI.PAIS = 'EL SALVADOR') THEN ACL.ESENCIA_REG_SAN_SAL
            ELSE ACL.ESENCIA_REG_SAN_PMA
        END AS ESENCIA_REG,
        ACL.LABORATORIO_REGS_PM_ AS FABRICANTE,
        ACL.FRANGANCIA AS FRAGANCIA,
        ACL.LOTE_PTY AS LOTE,
        ACL.GIFTCONTNEW AS SET_DE_REGALO,
        ACL.PAIS_ORIGEN AS ORIGEN,
        ACL.SUBCLASE,
        ACL.FINAL_PRODUCT_NAME AS PRODUCTO,
        ACL.NUM_REG_SAN_CR AS REGISTRO_SANITARIO_CR,
        ACL.NOM_REG_SAN_PMA AS REGISTRO_SANITARIO_PMA,
        ACL.NUM_REG_SAN_SAL AS REGISTRO_SANITARIO_SAL,
        ACL.CASE_PACK,
        F.DESCRIPCION AS FAMILIA,
        LIN.UNIDADESTOTAL AS CANTIDAD,
        (LIN.PRECIO - LIN.PRECIO * (LIN.DTO / 100)) AS PRECIO,
        LIN.DTO,
        LIN.TOTAL * CAB.FACTORMONEDA AS TOTAL,
        LIN.TOTAL AS TOTAL_LOC,
        TA.TOTAL_NETO,
        TA.TOTAL_BRUTO,
        TA.TOTAL_UNIDADES,
        DESCADIC_RS_PMA_CR
    FROM
        BBW_NEW.DBO.ALBVENTACAB AS CAB
    INNER JOIN
        BBW_NEW.DBO.ALBVENTALIN AS LIN ON CAB.NUMSERIE = LIN.NUMSERIE
                                    AND CAB.NUMALBARAN = LIN.NUMALBARAN
                                    AND CAB.N = LIN.N
    INNER JOIN
        BBW_NEW.DBO.ARTICULOS AS ART ON ART.CODARTICULO = LIN.CODARTICULO
    INNER JOIN
        BBW_NEW.DBO.ARTICULOSLIN AS ARL ON ARL.CODARTICULO = LIN.CODARTICULO
                                        AND ARL.COLOR = LIN.COLOR
                                        AND ARL.TALLA = LIN.TALLA
    INNER JOIN
        BBW_NEW.DBO.ARTICULOSCAMPOSLIBRES AS ACL ON ACL.CODARTICULO = LIN.CODARTICULO
    LEFT JOIN
        BBW_NEW.DBO.MARCA AS M ON M.CODMARCA = ART.MARCA
    LEFT JOIN
        BBW_NEW.DBO.DEPARTAMENTO AS D ON D.NUMDPTO = ART.DPTO
    LEFT JOIN
        BBW_NEW.DBO.FAMILIAS AS F ON F.NUMDPTO = ART.DPTO
                                AND F.NUMSECCION = ART.SECCION
                                AND F.NUMFAMILIA = ART.FAMILIA
    LEFT JOIN
        BBW_NEW.DBO.CLIENTES AS CLI ON CLI.CODCLIENTE = CAB.CODCLIENTE
    INNER JOIN
        TotalesAgregados AS TA ON CAB.NUMSERIEFAC = TA.NUMSERIEFAC
                            AND CAB.NUMFAC = TA.NUMFAC
    WHERE
        CAB.NUMSERIEFAC LIKE @NUMSERIEFAC
        AND CAB.NUMFAC = @NUMFAC;
`

export const reporteVSFA = `
    WITH TotalesAgregados AS (
        SELECT
            CAB.NUMSERIEFAC,
            CAB.NUMFAC,
            SUM(LIN.TOTAL * CAB.FACTORMONEDA) AS TOTAL_NETO,
            SUM(LIN.TOTAL * CAB.FACTORMONEDA) AS TOTAL_BRUTO,
            SUM(LIN.UNIDADESTOTAL) AS TOTAL_UNIDADES
        FROM
            ALBVENTACAB AS CAB
        INNER JOIN
            ALBVENTALIN AS LIN ON CAB.NUMALBARAN = LIN.NUMALBARAN
                                        AND CAB.NUMSERIE = LIN.NUMSERIE
                                        AND CAB.N = LIN.N
        WHERE
            CAB.NUMSERIEFAC LIKE @NUMSERIEFAC
            AND CAB.NUMFAC = @NUMFAC
        GROUP BY
            CAB.NUMSERIEFAC,
            CAB.NUMFAC
    )

    --SELECT * FROM FACTURASVENTA WHERE NUMSERIE = 'V4VF' AND NUMFACTURA = 2517

    SELECT
            X.REFPROVEEDOR_ESTILO AS REFERENCIA,
            X.CODIGO_BARRAS AS CODIGO,
            X.TALLA AS TALLA_CODIGO,
            CASE
                WHEN X.TALLA = 'NA' THEN X.SIZE_DESC_BA COLLATE MODERN_SPANISH_CI_AS
                ELSE X.TALLA COLLATE MODERN_SPANISH_CI_AS
            END AS CONTENIDO,
            COALESCE(X.ACL_NOM_SANITARIO, X.ART_DESCRIPCION_GRAL) COLLATE MODERN_SPANISH_CI_AS AS DESCRIPCION_GENERAL, 
            X.DESCRIPCION_ESP COLLATE MODERN_SPANISH_CI_AS AS DETALLE_ADUANAL,
            X.COMPOSICION AS COMPOSICION,
            '' AS NOMBRE_COMERCIAL_ALTER, 
            X.ESENCIA AS FRAGANCIA,
            NOMESENREGSAN AS ESENCIA_REG,
            X.GIFTSETCONTENT AS SET_REGALO,
            REGSANITARIO AS NUM_REG,
            X.ACL_NUM_LOTE COLLATE MODERN_SPANISH_CI_AS AS NUM_LOTE,
            FECHAVEN AS FECHA_VENCIMIENTO,
            X.ACL_FABRICANTE COLLATE MODERN_SPANISH_CI_AS AS FABRICANTE,
            X.PAIS_ORIGEN COLLATE MODERN_SPANISH_CI_AS AS ORIGEN,
            X.MARCA_DESC COLLATE MODERN_SPANISH_CI_AS AS MARCA,
            X.PAIS_CLIENTE COLLATE MODERN_SPANISH_CI_AS PAIS_CLIENTE,
            X.DEPARTAMENTO_DESC COLLATE MODERN_SPANISH_CI_AS AS DEPARTAMENTO,
            X.CANTIDAD,
            X.PRECIO_UNITARIO_BASE AS PRECIO,
            X.TOTAL_LINEA_BASE AS TOTAL,
            X.TOTAL_NETO,
            X.TOTAL_BRUTO,
            X.TOTAL_UNIDADES

        FROM
        (
            SELECT
                CAB.NUMSERIEFAC, CAB.NUMFAC, LIN.TALLA, LIN.UNIDADESTOTAL AS CANTIDAD, LIN.TOTAL, CAB.FACTORMONEDA,
                (SELECT TOP 1 AL.CODBARRAS FROM ARTICULOSLIN AL WHERE AL.CODARTICULO = LIN.CODARTICULO AND AL.TALLA = LIN.TALLA AND AL.COLOR = LIN.COLOR) AS CODIGO_BARRAS,
                (SELECT TOP 1 CLI.PAIS FROM CLIENTES CLI WHERE CLI.CODCLIENTE = CAB.CODCLIENTE) AS PAIS_CLIENTE,
                (SELECT TOP 1 A.REFPROVEEDOR FROM ARTICULOS A WHERE A.CODARTICULO = LIN.CODARTICULO) AS REFPROVEEDOR_ESTILO,
                (SELECT TOP 1 A.DESCRIPCION FROM ARTICULOS A WHERE A.CODARTICULO = LIN.CODARTICULO) AS ART_DESCRIPCION_GRAL,
                (SELECT TOP 1 A.DESCRIPADIC FROM ARTICULOS A WHERE A.CODARTICULO = LIN.CODARTICULO) AS ART_DETALLE_ADIC,
                (SELECT TOP 1 D.DESCRIPCION FROM DEPARTAMENTO D, ARTICULOS A WHERE D.NUMDPTO = A.DPTO AND A.CODARTICULO = LIN.CODARTICULO) AS DEPARTAMENTO_DESC,
                (SELECT TOP 1 M.DESCRIPCION FROM MARCA M, ARTICULOS A WHERE M.CODMARCA = A.MARCA AND A.CODARTICULO = LIN.CODARTICULO) AS MARCA_DESC,
                ACL.NUMLOTE AS ACL_NUM_LOTE,
                ACL.FABRICADO AS ACL_FABRICANTE,
                ACL.COMPOSICION_ESP AS COMPOSICION,
                ACL.REGSANITARIO,
                ACL.NOMESENREGSAN,
                ACL.FECHAVEN,
                ACL.GIFTSETCONTENT,
                ACL.DESCRIPCION_ESP,
                ACL.PAIS_ORIGEN,
                TA.TOTAL_NETO,
                TA.TOTAL_BRUTO,
                ACL.ESENCIA,
                TA.TOTAL_UNIDADES,
                ACL.DESCRIPCION_ESP AS ACL_NOM_SANITARIO,
                ACL.SIZE_DESC_BA,
                (LIN.TOTAL * CAB.FACTORMONEDA) / CASE WHEN LIN.UNIDADESTOTAL = 0 THEN 1 ELSE LIN.UNIDADESTOTAL END AS PRECIO_UNITARIO_BASE,
                LIN.TOTAL * CAB.FACTORMONEDA AS TOTAL_LINEA_BASE

            FROM
                ALBVENTACAB AS CAB
                INNER JOIN ALBVENTALIN AS LIN ON (CAB.NUMSERIE = LIN.NUMSERIE AND CAB.NUMALBARAN = LIN.NUMALBARAN AND CAB.N = LIN.N)
                INNER JOIN ARTICULOSCAMPOSLIBRES ACL ON (ACL.CODARTICULO = LIN.CODARTICULO)
                INNER JOIN TotalesAgregados AS TA ON CAB.NUMSERIEFAC = TA.NUMSERIEFAC AND CAB.NUMFAC = TA.NUMFAC
            WHERE
                CAB.NUMSERIEFAC LIKE @NUMSERIEFAC
                AND CAB.NUMFAC = @NUMFAC

        ) X
`

export const reporteVSBA = `
    WITH TotalesAgregados AS (
        SELECT
            CAB.NUMSERIEFAC,
            CAB.NUMFAC,
            SUM(LIN.TOTAL * CAB.FACTORMONEDA) AS TOTAL_NETO,
            SUM(LIN.TOTAL * CAB.FACTORMONEDA) AS TOTAL_BRUTO,
            SUM(LIN.UNIDADESTOTAL) AS TOTAL_UNIDADES
        FROM
            ALBVENTACAB AS CAB
        INNER JOIN
            ALBVENTALIN AS LIN ON CAB.NUMALBARAN = LIN.NUMALBARAN
                                        AND CAB.NUMSERIE = LIN.NUMSERIE
                                        AND CAB.N = LIN.N
        WHERE
            CAB.NUMSERIEFAC LIKE @NUMSERIEFAC
            AND CAB.NUMFAC = @NUMFAC
        GROUP BY
            CAB.NUMSERIEFAC,
            CAB.NUMFAC
    )

SELECT
        -- 1. IDENTIFICADORES Y CODIGOS
        X.REFPROVEEDOR_ESTILO COLLATE MODERN_SPANISH_CI_AS AS REFERENCIA,
        X.CODIGO_BARRAS AS CODIGO,
        X.TALLA COLLATE MODERN_SPANISH_CI_AS AS TALLA_CODIGO,
        
        -- 2. CONTENIDO Y DESCRIPCIONES
        CASE
            WHEN X.TALLA = 'NA' THEN X.SIZE_DESC_BA COLLATE MODERN_SPANISH_CI_AS
            ELSE X.TALLA COLLATE MODERN_SPANISH_CI_AS
        END AS CONTENIDO,
        
        -- Descripción General
        COALESCE(X.ART_DESCRIPCION_GRAL, X.ACL_STYLE_DESC) COLLATE MODERN_SPANISH_CI_AS AS DESCRIPCION_GENERAL, 
        
        -- Descripción Aduanal / Detalle (Solo se dejan los campos compatibles que no dieron error)
        COALESCE(X.ACL_DESCRIP_ADUANA, X.ART_DETALLE_ADIC) COLLATE MODERN_SPANISH_CI_AS AS DETALLE_ADUANAL,
        
        -- 3. INFORMACION ADICIONAL DEL PRODUCTO
        X.ACL_COMPOSICION_ADUANA COLLATE MODERN_SPANISH_CI_AS AS COMPOSICION,
        X.ACL_COLOR_ALTER COLLATE MODERN_SPANISH_CI_AS AS NOMBRE_COMERCIAL_ALTER,
        
        -- Campos que daban error y ahora son NULL/'' para compatibilidad
        '' AS FRAGANCIA_MAESTRO,
        '' AS ESENCIA_REGISTRO,
        '' AS SET_REGALO,
        
        -- 4. REGISTRO SANITARIO Y LOTE
        '' AS NUM_REGISTRO,
        X.ACL_NUM_LOTE COLLATE MODERN_SPANISH_CI_AS AS NUM_LOTE,
        NULL AS FECHA_VENCIMIENTO,
        X.ACL_FABRICANTE COLLATE MODERN_SPANISH_CI_AS AS FABRICANTE,

        -- 5. ORIGEN Y MARCA
        X.ACL_PAIS_ORIGEN_ADUANA COLLATE MODERN_SPANISH_CI_AS AS ORIGEN,
        X.MARCA_DESC COLLATE MODERN_SPANISH_CI_AS AS MARCA,
        X.PAIS_CLIENTE COLLATE MODERN_SPANISH_CI_AS,
        X.DEPARTAMENTO_DESC COLLATE MODERN_SPANISH_CI_AS AS DEPARTAMENTO,
        
        -- 6. VALORES
        X.CANTIDAD AS CANTIDAD,
        X.PRECIO_UNITARIO_BASE AS PRECIO,
        X.TOTAL_LINEA_BASE AS TOTAL,
		X.TOTAL_NETO,
		X.TOTAL_BRUTO,
		X.TOTAL_UNIDADES

    FROM
    (
        SELECT
            CAB.NUMSERIEFAC, CAB.NUMFAC, LIN.TALLA, LIN.UNIDADESTOTAL AS CANTIDAD, LIN.TOTAL, CAB.FACTORMONEDA,

            -- Lookups base
            (SELECT TOP 1 AL.CODBARRAS FROM ARTICULOSLIN AL WHERE AL.CODARTICULO = LIN.CODARTICULO AND AL.TALLA = LIN.TALLA AND AL.COLOR = LIN.COLOR) AS CODIGO_BARRAS,
            (SELECT TOP 1 CLI.PAIS FROM CLIENTES CLI WHERE CLI.CODCLIENTE = CAB.CODCLIENTE) AS PAIS_CLIENTE,
            (SELECT TOP 1 A.REFPROVEEDOR FROM ARTICULOS A WHERE A.CODARTICULO = LIN.CODARTICULO) AS REFPROVEEDOR_ESTILO,
            ACL.DESCRIPESP_ADUANACOL AS ART_DESCRIPCION_GRAL,
            (SELECT TOP 1 A.DESCRIPADIC FROM ARTICULOS A WHERE A.CODARTICULO = LIN.CODARTICULO) AS ART_DETALLE_ADIC,
            (SELECT TOP 1 D.DESCRIPCION FROM DEPARTAMENTO D, ARTICULOS A WHERE D.NUMDPTO = A.DPTO AND A.CODARTICULO = LIN.CODARTICULO) AS DEPARTAMENTO_DESC,
            (SELECT TOP 1 M.DESCRIPCION FROM MARCA M, ARTICULOS A WHERE M.CODMARCA = A.MARCA AND A.CODARTICULO = LIN.CODARTICULO) AS MARCA_DESC,

            -- ACL (Campos Libres) - SELECCIONANDO SOLO CAMPOS EXISTENTES EN ESTE ESQUEMA
            -- Los campos que daban error (DESCRIPCION_ESP, REGSANITARIO, etc.) NO se seleccionan aquí.
            
            ACL.COMPESPA AS ACL_COMPOSICION_ADUANA,
            ACL.PAISORIG AS ACL_PAIS_ORIGEN_ADUANA,
            ACL.DESCADUAN AS ACL_DESCRIP_ADUANA,
            ACL.NUMLOTE AS ACL_NUM_LOTE,
            ACL.FABRICADO AS ACL_FABRICANTE,
            ACL.STYLE_DESCRIPCION AS ACL_STYLE_DESC,
            ACL.COLORALTER AS ACL_COLOR_ALTER,
            ACL.SIZE_DESC_BA, 
			TA.TOTAL_NETO,
			TA.TOTAL_BRUTO,
			TA.TOTAL_UNIDADES,
            --ACL.NOMSANITARIO AS ACL_NOM_SANITARIO, -- Campo de la antigua consulta que no dio error en la nueva

            -- Cálculo de Precios
            (LIN.TOTAL * CAB.FACTORMONEDA) / CASE WHEN LIN.UNIDADESTOTAL = 0 THEN 1 ELSE LIN.UNIDADESTOTAL END AS PRECIO_UNITARIO_BASE,
            LIN.TOTAL * CAB.FACTORMONEDA AS TOTAL_LINEA_BASE

        FROM
            ALBVENTACAB AS CAB
            INNER JOIN ALBVENTALIN AS LIN ON (CAB.NUMSERIE = LIN.NUMSERIE AND CAB.NUMALBARAN = LIN.NUMALBARAN AND CAB.N = LIN.N)
            INNER JOIN ARTICULOSCAMPOSLIBRES ACL ON (ACL.CODARTICULO = LIN.CODARTICULO)
			INNER JOIN TotalesAgregados AS TA ON CAB.NUMSERIEFAC = TA.NUMSERIEFAC AND CAB.NUMFAC = TA.NUMFAC
        WHERE
            CAB.NUMSERIEFAC LIKE @NUMSERIEFAC
            AND CAB.NUMFAC = @NUMFAC
    ) X
`