export const reporteGeneral = `
    WITH TotalesAgregados AS (
        SELECT
            CAB.NUMSERIEFAC,
            CAB.NUMFAC,
            SUM(LIN.TOTAL * CAB.FACTORMONEDA) AS TOTAL_NETO,
            SUM((LIN.PRECIO * CAB.FACTORMONEDA) * LIN.UNIDADESTOTAL) AS TOTAL_BRUTO,
            SUM(LIN.UNIDADESTOTAL) AS TOTAL_UNIDADES
        FROM
            BBW_NEW.DBO.ALBVENTACAB AS CAB
        INNER JOIN
            BBW_NEW.DBO.ALBVENTALIN AS LIN ON CAB.NUMALBARAN = LIN.NUMALBARAN
                                        AND CAB.NUMSERIE = LIN.NUMSERIE
                                        AND CAB.N = LIN.N
        WHERE
            CAB.NUMSERIEFAC LIKE @NUMSERIEFAC
            AND CAB.NUMFAC = @NUMFAC
        GROUP BY
            CAB.NUMSERIEFAC,
            CAB.NUMFAC
    )
    SELECT
        LIN.REFERENCIA AS ARTICULO,
        ART.REFPROVEEDOR AS CODIGO,
        LIN.TALLA AS CONTENIDO,
        LIN.COLOR,
        ARL.CODBARRAS AS CODBARRAS,
        M.DESCRIPCION AS MARCA,
        ART.DESCRIPCION AS DESCRIPCION,
        D.DESCRIPCION AS DEPARTAMENTO,
        ACL.DESCRIP_ADIC AS DETALLE,
        ACL.COMPOESP AS COMPOSICION,
        CASE
            WHEN (CLI.PAIS = 'COSTA RICA') THEN ACL.NUM_REG_SAN_CR
            WHEN (CLI.PAIS = 'EL SALVADOR') THEN ACL.NUM_REG_SAN_SAL
            ELSE ACL.NUM_REG_SAN_PAN
        END AS NUM_REG,
        CASE
            WHEN (CLI.PAIS = 'COSTA RICA') THEN ACL.NOM_REG_SAN_CR
            WHEN (CLI.PAIS = 'EL SALVADOR') THEN ACL.NOM_REG_SAN_SAL
            ELSE ACL.NOM_REG_SAN_PMA
        END AS DESCRIPCION_REG,
        CASE
            WHEN (CLI.PAIS = 'COSTA RICA') THEN ACL.ESENCIA_REG_SAN_CR
            WHEN (CLI.PAIS = 'EL SALVADOR') THEN ACL.ESENCIA_REG_SAN_SAL
            ELSE ACL.ESENCIA_REG_SAN_PMA
        END AS ESENCIA_REG,
        ACL.LABORATORIO_REGS_PM_ AS FABRICANTE,
        ACL.FRANGANCIA AS FRAGANCIA,
        ACL.LOTE_PTY AS LOTE,
        ACL.GIFTCONTNEW AS SET_DE_REGALO,
        ACL.PAIS_ORIGEN AS ORIGEN,
        ACL.SUBCLASE,
        ACL.FINAL_PRODUCT_NAME AS PRODUCTO,
        ACL.NUM_REG_SAN_CR AS REGISTRO_SANITARIO_CR,
        ACL.NOM_REG_SAN_PMA AS REGISTRO_SANITARIO_PMA,
        ACL.NUM_REG_SAN_SAL AS REGISTRO_SANITARIO_SAL,
        ACL.CASE_PACK,
        F.DESCRIPCION AS FAMILIA,
        LIN.UNIDADESTOTAL AS CANTIDAD,
        (LIN.PRECIO - LIN.PRECIO * (LIN.DTO / 100)) AS PRECIO,
        LIN.DTO,
        LIN.TOTAL * CAB.FACTORMONEDA AS TOTAL,
        LIN.TOTAL AS TOTAL_LOC,
        TA.TOTAL_NETO,
        TA.TOTAL_BRUTO,
        TA.TOTAL_UNIDADES
    FROM
        BBW_NEW.DBO.ALBVENTACAB AS CAB
    INNER JOIN
        BBW_NEW.DBO.ALBVENTALIN AS LIN ON CAB.NUMSERIE = LIN.NUMSERIE
                                    AND CAB.NUMALBARAN = LIN.NUMALBARAN
                                    AND CAB.N = LIN.N
    INNER JOIN
        BBW_NEW.DBO.ARTICULOS AS ART ON ART.CODARTICULO = LIN.CODARTICULO
    INNER JOIN
        BBW_NEW.DBO.ARTICULOSLIN AS ARL ON ARL.CODARTICULO = LIN.CODARTICULO
                                        AND ARL.COLOR = LIN.COLOR
                                        AND ARL.TALLA = LIN.TALLA
    INNER JOIN
        BBW_NEW.DBO.ARTICULOSCAMPOSLIBRES AS ACL ON ACL.CODARTICULO = LIN.CODARTICULO
    LEFT JOIN
        BBW_NEW.DBO.MARCA AS M ON M.CODMARCA = ART.MARCA
    LEFT JOIN
        BBW_NEW.DBO.DEPARTAMENTO AS D ON D.NUMDPTO = ART.DPTO
    LEFT JOIN
        BBW_NEW.DBO.FAMILIAS AS F ON F.NUMDPTO = ART.DPTO
                                AND F.NUMSECCION = ART.SECCION
                                AND F.NUMFAMILIA = ART.FAMILIA
    LEFT JOIN
        BBW_NEW.DBO.CLIENTES AS CLI ON CLI.CODCLIENTE = CAB.CODCLIENTE
    INNER JOIN
        TotalesAgregados AS TA ON CAB.NUMSERIEFAC = TA.NUMSERIEFAC
                            AND CAB.NUMFAC = TA.NUMFAC
    WHERE
        CAB.NUMSERIEFAC LIKE @NUMSERIEFAC
        AND CAB.NUMFAC = @NUMFAC;
`